name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip=23.0.1
  - scikit-learn
  - scipy=1.10.1
  - pandas=1.4.1
  - xgboost=2.0.3
  - azure-ai-ml
  - azure-core
  - azure-identity
  - joblib
  - plotly
  - matplotlib
  - seaborn
  - jupyter
  - pip:
      - azureml-defaults==1.53.0
      - inference-schema[numpy-support]==1.5.1
